import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import SiteHeader from "@/components/layouts/site-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout(props: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen flex-col">
      <SiteHeader />
      <main className="flex w-full flex-col overflow-hidden">
        {props.children}
      </main>
    </div>
  );
}
